// <auto-generated />
using System;
using FoodSeekerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodSeekerAPI.Migrations
{
    [DbContext(typeof(FoodSeekerContext))]
    partial class FoodSeekerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodSeekerAPI.Models.DonatorProfile", b =>
                {
                    b.Property<long>("DonatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<float>("AverageScore")
                        .HasColumnType("real");

                    b.Property<TimeOnly>("DonationEnds")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("DonationStarts")
                        .HasColumnType("time");

                    b.Property<int>("FavoritesCount")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DonatorId");

                    b.ToTable("DonatorProfiles");
                });

            modelBuilder.Entity("FoodSeekerAPI.Models.FavoriteDonator", b =>
                {
                    b.Property<long>("FavouriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FavouriteId"));

                    b.Property<long>("DonatorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FavoritedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("SeekerId")
                        .HasColumnType("bigint");

                    b.HasKey("FavouriteId");

                    b.HasIndex("DonatorId");

                    b.HasIndex("SeekerId");

                    b.ToTable("FavoriteDonators");
                });

            modelBuilder.Entity("FoodSeekerAPI.Models.Feedback", b =>
                {
                    b.Property<long>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FeedbackId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DonatorId")
                        .HasColumnType("bigint");

                    b.Property<long>("FromUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("DonatorId");

                    b.HasIndex("FromUserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("FoodSeekerAPI.Models.FoodItem", b =>
                {
                    b.Property<long>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FoodId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("DonatorId")
                        .HasColumnType("bigint");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBringPack")
                        .HasColumnType("bit")
                        .HasColumnName("IsBringPack");

                    b.Property<bool>("IsEatIn")
                        .HasColumnType("bit")
                        .HasColumnName("IsEatIn");

                    b.Property<bool>("IsTakeAway")
                        .HasColumnType("bit")
                        .HasColumnName("IsTakeAway");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("FoodId");

                    b.HasIndex("DonatorId");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("FoodSeekerAPI.Models.NotificationLog", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("FoodSeekerAPI.Models.PickupIntent", b =>
                {
                    b.Property<long>("IntentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IntentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint");

                    b.Property<long>("SeekerId")
                        .HasColumnType("bigint");

                    b.HasKey("IntentId");

                    b.HasIndex("FoodId");

                    b.HasIndex("SeekerId");

                    b.ToTable("PickupIntents");
                });

            modelBuilder.Entity("FoodSeekerAPI.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDonator")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FoodSeekerAPI.Models.UserDeviceToken", b =>
                {
                    b.Property<long>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Platform")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDeviceTokens");
                });

            modelBuilder.Entity("FoodSeekerAPI.Models.DonatorProfile", b =>
                {
                    b.HasOne("FoodSeekerAPI.Models.User", "User")
                        .WithOne("DonatorProfile")
                        .HasForeignKey("FoodSeekerAPI.Models.DonatorProfile", "DonatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodSeekerAPI.Models.FavoriteDonator", b =>
                {
                    b.HasOne("FoodSeekerAPI.Models.DonatorProfile", "DonatorProfile")
                        .WithMany()
                        .HasForeignKey("DonatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodSeekerAPI.Models.User", "Seeker")
                        .WithMany("Favorites")
                        .HasForeignKey("SeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonatorProfile");

                    b.Navigation("Seeker");
                });

            modelBuilder.Entity("FoodSeekerAPI.Models.Feedback", b =>
                {
                    b.HasOne("FoodSeekerAPI.Models.DonatorProfile", "DonatorProfile")
                        .WithMany()
                        .HasForeignKey("DonatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodSeekerAPI.Models.User", "FromUser")
                        .WithMany("Feedbacks")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonatorProfile");

                    b.Navigation("FromUser");
                });

            modelBuilder.Entity("FoodSeekerAPI.Models.FoodItem", b =>
                {
                    b.HasOne("FoodSeekerAPI.Models.DonatorProfile", "DonatorProfile")
                        .WithMany()
                        .HasForeignKey("DonatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonatorProfile");
                });

            modelBuilder.Entity("FoodSeekerAPI.Models.NotificationLog", b =>
                {
                    b.HasOne("FoodSeekerAPI.Models.User", "User")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodSeekerAPI.Models.PickupIntent", b =>
                {
                    b.HasOne("FoodSeekerAPI.Models.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodSeekerAPI.Models.User", "User")
                        .WithMany("PickupIntents")
                        .HasForeignKey("SeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodSeekerAPI.Models.UserDeviceToken", b =>
                {
                    b.HasOne("FoodSeekerAPI.Models.User", "User")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodSeekerAPI.Models.User", b =>
                {
                    b.Navigation("DeviceTokens");

                    b.Navigation("DonatorProfile")
                        .IsRequired();

                    b.Navigation("Favorites");

                    b.Navigation("Feedbacks");

                    b.Navigation("NotificationLogs");

                    b.Navigation("PickupIntents");
                });
#pragma warning restore 612, 618
        }
    }
}
